/**
 * Storage for in-flight sign-ins and established Owner sessions.
 *
 * The security-relevant decisions in this file are all about *where* a check
 * happens. Every "is this still valid?" test is expressed as a SQL predicate
 * rather than as a comparison in TypeScript after a read. A read-then-decide
 * pair is two steps that another request can interleave with, which is exactly
 * how a one-use token gets used twice. Written as a conditional `UPDATE ...
 * RETURNING`, validity and consumption are one atomic step, and SQLite's
 * single-writer guarantee does the rest.
 *
 * Callers therefore never see an expired or consumed row and cannot forget to
 * check for one — the absence of a returned row *is* the rejection.
 */

import { Repository } from "./repository";
import {
  ABSOLUTE_TTL_SECONDS,
  ATTEMPT_TTL_SECONDS,
  IDLE_TTL_SECONDS,
  TOUCH_INTERVAL_SECONDS,
} from "../auth/policy";
import { timestamp, timestampAfter } from "../auth/tokens";

export interface AttemptRecord {
  attemptTokenDigest: string;
  stateDigest: string;
  pkceVerifier: string;
}

export interface OwnerSession {
  tokenDigest: string;
  githubUserId: number;
  csrfToken: string;
  createdAt: string;
  lastSeenAt: string;
  idleExpiresAt: string;
  absoluteExpiresAt: string;
}

interface SessionRow {
  token_digest: string;
  github_user_id: number;
  csrf_token: string;
  created_at: string;
  last_seen_at: string;
  idle_expires_at: string;
  absolute_expires_at: string;
}

function toSession(row: SessionRow): OwnerSession {
  return {
    tokenDigest: row.token_digest,
    githubUserId: row.github_user_id,
    csrfToken: row.csrf_token,
    createdAt: row.created_at,
    lastSeenAt: row.last_seen_at,
    idleExpiresAt: row.idle_expires_at,
    absoluteExpiresAt: row.absolute_expires_at,
  };
}

export class OwnerAuthRepository extends Repository {
  /**
   * Records a sign-in attempt and sweeps expired ones.
   *
   * The sweep rides along with the write that creates work rather than running
   * on a timer, so an idle server does no background work and a server under a
   * flood of abandoned attempts cleans up in proportion to the flood.
   */
  createAttempt(attempt: AttemptRecord, now: Date = new Date()): void {
    this.transaction(() => {
      this.database
        .query("DELETE FROM oauth_attempts WHERE expires_at <= ?")
        .run(timestamp(now));

      this.database
        .query(
          `INSERT INTO oauth_attempts (
             attempt_token_digest, state_digest, pkce_verifier,
             created_at, expires_at, consumed_at
           ) VALUES (?, ?, ?, ?, ?, NULL)`
        )
        .run(
          attempt.attemptTokenDigest,
          attempt.stateDigest,
          attempt.pkceVerifier,
          timestamp(now),
          timestampAfter(ATTEMPT_TTL_SECONDS, now)
        );
    });
  }

  /**
   * Claims an attempt, returning its PKCE verifier exactly once.
   *
   * Both digests must match the same row: the state proves the callback came
   * from a redirect this server issued, and the attempt token — which only ever
   * lived in a cookie — proves it arrived in the browser that started it. An
   * attacker who observes a `state` in a redirect URL still holds nothing that
   * matches the cookie half.
   *
   * Returns null for missing, mismatched, expired, or already-consumed
   * attempts, without distinguishing between them.
   */
  consumeAttempt(
    attemptTokenDigest: string,
    stateDigest: string,
    now: Date = new Date()
  ): string | null {
    const row = this.database
      .query(
        `UPDATE oauth_attempts
            SET consumed_at = ?
          WHERE attempt_token_digest = ?
            AND state_digest = ?
            AND consumed_at IS NULL
            AND expires_at > ?
        RETURNING pkce_verifier`
      )
      .get(timestamp(now), attemptTokenDigest, stateDigest, timestamp(now)) as {
      pkce_verifier: string;
    } | null;

    return row?.pkce_verifier ?? null;
  }

  /**
   * Starts a session, ending any other.
   *
   * The revoke and the insert share a transaction so there is never an instant
   * with two live sessions, and the new token is always freshly generated by
   * the caller — a session identifier that survived sign-in would be a session
   * fixation vector, so no code path reuses one.
   */
  createSession(
    session: {
      tokenDigest: string;
      githubUserId: number;
      csrfToken: string;
    },
    now: Date = new Date()
  ): OwnerSession {
    return this.transaction(() => {
      this.database
        .query(
          "UPDATE owner_sessions SET revoked_at = ? WHERE revoked_at IS NULL"
        )
        .run(timestamp(now));

      const row = this.database
        .query(
          `INSERT INTO owner_sessions (
             token_digest, github_user_id, csrf_token,
             created_at, last_seen_at, idle_expires_at, absolute_expires_at,
             revoked_at
           ) VALUES (?, ?, ?, ?, ?, ?, ?, NULL)
           RETURNING *`
        )
        .get(
          session.tokenDigest,
          session.githubUserId,
          session.csrfToken,
          timestamp(now),
          timestamp(now),
          timestampAfter(IDLE_TTL_SECONDS, now),
          timestampAfter(ABSOLUTE_TTL_SECONDS, now)
        ) as SessionRow;

      return toSession(row);
    });
  }

  /**
   * The live session for a token digest, or null.
   *
   * Both expiries are checked in the query. A caller cannot receive a session
   * that has timed out and then forget to look at the timestamps.
   */
  findActiveSession(
    tokenDigest: string,
    now: Date = new Date()
  ): OwnerSession | null {
    const row = this.database
      .query(
        `SELECT * FROM owner_sessions
          WHERE token_digest = ?
            AND revoked_at IS NULL
            AND idle_expires_at > ?
            AND absolute_expires_at > ?`
      )
      .get(tokenDigest, timestamp(now), timestamp(now)) as SessionRow | null;

    return row ? toSession(row) : null;
  }

  /**
   * Pushes the idle deadline forward, at most once every few minutes.
   *
   * `absolute_expires_at` is deliberately not in the `SET` list. Twelve hours
   * after sign-in the session ends regardless of activity, and the only way to
   * guarantee that is for no code to be able to move it.
   */
  touchSession(tokenDigest: string, now: Date = new Date()): void {
    this.database
      .query(
        `UPDATE owner_sessions
            SET last_seen_at = ?,
                idle_expires_at = ?
          WHERE token_digest = ?
            AND revoked_at IS NULL
            AND last_seen_at <= ?`
      )
      .run(
        timestamp(now),
        timestampAfter(IDLE_TTL_SECONDS, now),
        tokenDigest,
        timestampAfter(-TOUCH_INTERVAL_SECONDS, now)
      );
  }

  revokeSession(tokenDigest: string, now: Date = new Date()): void {
    this.database
      .query(
        `UPDATE owner_sessions
            SET revoked_at = ?
          WHERE token_digest = ? AND revoked_at IS NULL`
      )
      .run(timestamp(now), tokenDigest);
  }
}
